package com.example.haircut.backend;

public enum FLAGS {
    SUCCESS, INVALID_FNAME, INVALID_LNAME, INVALID_EMAIL, INVALID_CODE, INVALID_PASSWORD, INVALID_NEW_PASSWORD, PASSWORD_MISMATCH, INVALID_USER, ERROR,
    EMAIL_NOT_REGISTERED, INCORRECT_CREDENTIALS, EMAIL_ALREADY_REGISTERED
}