[versions]
agp = "8.5.2"
dnsjava = "3.6.2"
firebaseBom = "33.5.1"
#javaJwt = "4.4.0"
googleServices = "4.4.2"
kotlin = "2.0.20"
coreKtx = "1.13.1"
junit = "4.13.2"
junitVersion = "1.2.1"
espressoCore = "3.6.1"
appcompat = "1.7.0"
material = "1.12.0"
activity = "1.9.3"
constraintlayout = "2.1.4"
junitJupiter = "5.11.1"
junitPlatformLauncher = "1.11.1"
slf4jAndroid = "1.7.36"
slf4jSimple = "2.0.16"
firebaseDatabase = "21.0.0"
googleGmsGoogleServices = "4.4.2"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
dnsjava = { module = "dnsjava:dnsjava", version.ref = "dnsjava" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
firebase-analytics = { module = "com.google.firebase:firebase-analytics" }
firebase-auth = { module = "com.google.firebase:firebase-auth" }
firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebaseBom" }
firebase-functions = { module = "com.google.firebase:firebase-functions" }
google-services = { module = "com.google.gms:google-services", version.ref = "googleServices" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
androidx-activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }

androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
junit-jupiter-api = { group = "org.junit.jupiter", name = "junit-jupiter-api", version.ref = "junitJupiter" }
junit-jupiter-engine = { group = "org.junit.jupiter", name = "junit-jupiter-engine", version.ref = "junitJupiter"}
junit-jupiter-params =  { group = "org.junit.jupiter", name = "junit-jupiter-params", version.ref = "junitJupiter"}
junit-platform-launcher =  { group = "org.junit.platform", name = "junit-platform-launcher", version.ref = "junitPlatformLauncher"}
slf4j-android = { module = "org.slf4j:slf4j-android", version.ref = "slf4jAndroid" }
slf4j-simple = { module = "org.slf4j:slf4j-simple", version.ref = "slf4jSimple" }
firebase-database = { group = "com.google.firebase", name = "firebase-database", version.ref = "firebaseDatabase" }
[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }